=== polyipseity/nucleus/src/users/schemas/dev-repos.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "platformString": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "additionalProperties": false,
          "properties": {
            "macos": {
              "type": "string"
            },
            "nixos": {
              "type": "string"
            },
            "windows": {
              "type": "string"
            }
          },
          "required": ["macos", "nixos", "windows"],
          "type": "object"
        }
      ]
    }
  },
  "description": "Development repository provisioning configuration.",
  "properties": {
    "$schema": {
      "description": "Reference to this schema file.",
      "type": "string"
    },
    "enable": {
      "type": "boolean"
    },
    "gitHubUsername": {
      "type": "string"
    },
    "repositories": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "symlinkFromRepoRoot": {
            "type": "boolean"
          },
          "target": {
            "$ref": "#/definitions/platformString"
          },
          "url": {
            "type": "string"
          }
        },
        "required": ["name"],
        "type": "object"
      },
      "type": "array"
    },
    "submoduleDirectories": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "path": {
            "type": "string"
          },
          "recursive": {
            "type": "boolean"
          }
        },
        "required": ["path"],
        "type": "object"
      },
      "type": "array"
    }
  },
  "required": ["enable", "gitHubUsername", "repositories"],
  "type": "object"
}

=== polyipseity/nucleus/src/users/polyipseity/dev-repos.json
{
  "$schema": "../schemas/dev-repos.schema.json",
  "enable": true,
  "gitHubUsername": "polyipseity",
  "repositories": [
    {
      "name": "nucleus",
      "symlinkFromRepoRoot": true,
      "target": {
        "macos": "dev/nucleus",
        "nixos": "dev/nucleus",
        "windows": "dev\\nucleus"
      }
    },
    {
      "name": "monorepo",
      "target": {
        "macos": "dev/monorepo",
        "nixos": "dev/monorepo",
        "windows": "dev\\monorepo"
      },
      "url": "git@github.com:polyipseity/monorepo.git"
    },
    {
      "name": "monorepo-private",
      "target": {
        "macos": "dev/monorepo-private",
        "nixos": "dev/monorepo-private",
        "windows": "dev\\monorepo-private"
      },
      "url": "git@github.com:polyipseity/monorepo-private.git"
    }
  ],
  "submoduleDirectories": [
    {
      "path": "dev/monorepo",
      "recursive": false
    },
    {
      "path": "dev/monorepo-private",
      "recursive": false
    },
    {
      "path": "dev/monorepo/self/obsidian-monorepo",
      "recursive": true
    },
    {
      "path": "dev/monorepo-private/orgs/*",
      "recursive": false
    }
  ]
}
